-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID,atr.AUTHOR_NAME, BOOK.CATEGORY,
        sum(BOOK.PRICE*s.SALES) TOTAL_SALES
FROM BOOK join AUTHOR atr on BOOK.AUTHOR_ID =atr.AUTHOR_ID join BOOK_SALES s on BOOK.BOOK_ID=s.BOOK_ID
WHERE date_format(s.SALES_DATE,'%Y-%m')='2022-01'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY desc