-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, sum(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B inner join USED_GOODS_USER U on B.WRITER_ID=U.USER_ID
WHERE B.STATUS='DONE'
GROUP BY 1,2
Having TOTAL_SALES>=700000
ORDER BY 3
 