-- 코드를 입력하세요
SELECT HALF.FLAVOR
FROM FIRST_HALF HALF inner join ICECREAM_INFO INFO on HALF.FLAVOR = INFO.FLAVOR
WHERE HALF.TOTAL_ORDER>3000 and INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY HALF.TOTAL_ORDER desc